import { ProgramPriorityType } from "../Logist/Logist.types";

import { DoerType } from "../Master/Master.types";

export type MasterProgramPartsRecordType = {
    ProgramName: string;
    RepeatIDProgram: string;
    UsedArea: number;
    ScrapFraction: number;
    MachineName: string;
    CuttingTimeProgram: string;
    PostDateTime: string;
    Material: string;
    Thickness: number;
    SheetLength: number;
    SheetWidth: number;
    ArchivePacketID: number;
    TimeLineID: number;
    Comment: string;
    PostedByUserID: number;
    PierceQtyProgram: number;
    UserName: string;
    UserFirstName: string;
    UserLastName: string;
    UserEMail: string;
    LastLoginDate: string;
    path_to_ods: string;
    master_fio_id: number;
    time_program_started: string;
    time_program_finished: string;
    program_status: string;
    program_priority: ProgramPriorityType;
    id: number;
    created_at: string;
    updated_at: string;
    WONumber: string;
    CustomerName: string;
    WODate: string;
    OrderDate: string;
    WOData1: string;
    WOData2: string;
    DateCreated: string;
    wo_status: string;
    fio_doers: DoerType[];
    wo_number_id: number;
    program_id: number;
    storage_cell_id: number;
    done_by_fio_doer_id: number;
    PartName: string;
    QtyInProcess: number;
    PartLength: number;
    PartWidth: number;
    TrueArea: number;
    RectArea: number;
    TrueWeight: number;
    RectWeight: number;
    CuttingTimePart: string;
    CuttingLength: number;
    PierceQtyPart: number;
    NestedArea: number;
    TotalCuttingTime: string;
    MasterPartQty: number;
    WOState: string;
    DueDate: string;
    RevisionNumber: string;
    PK_PIP: string;
    part_status: string;
    qty_fact: number;
    SourceFileName: string | null;
};
